### ISSUE TITLE
RawRequest is nil in BeforeOnRequest method

### ISSUE THREAD

**Issue by belek** [RafPe/go-edgegrid#55]
My goal is to store body from request to particular URLs.  
To do that I implemented `OnBeforeRequest` interceptor where I am trying to use `httputil.DumpRequest` to get the body and then save it to DB. But I can't use `request.RawRequest` because it's nil. Also I enabled debug mode in client.

```
func (irc *RestyResponseInterceptorNomad) OnBeforeRequest(rc *resty.Client, req *resty.Request) error {
	fmt.Println("*** Is debug? ", rc.Debug)
	fmt.Println("*** Raw request: ", req.RawRequest)
	reqDump, err := httputil.DumpRequest(req.RawRequest, true)
	if err != nil {
		logrus.WithError(err).Error("failed to dump request in onAfterResponse method")
		return nil
	}

        .....
        .....
        .....
	return err
}
```

Output is:
```
*** Is debug?  true
*** Raw request:  <nil>
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
```

Why RawRequest is nil and what should I do to make it work well?

**Comment by RafPe** [comment]
@belek I think you should check with Resty framework which implements those middlewares.

**Comment by belek** [comment]
omg. sorry wrong tab.
